/************************************************************************
*
*	x86lst.c - Listing generator
*
*   Copyright (c) BrokenThorn Entertainment Co. All Rights Reserved.
*
************************************************************************/

#include "ncc.h"
#include <stdio.h>

PRIVATE FILE*    _in;
PRIVATE PSTRING  _fname;
PRIVATE unsigned _line;

PRIVATE void Close(void) {

	if (_in) {
		fclose(_in);
		_in = NULL;
		_fname = NULL;
		_line = NULL;
	}
}

PRIVATE void Open(IN PSTRING fname) {

	if (!fname)
		return;

	Close();
	_in = fopen(fname->val, "r");
	if (_in) {
		_fname = fname;
		_line = 1;
	}
}

PRIVATE void Goto(IN unsigned y) {

	int c;

	_line = 1;
	if (!_in)
		return;
	rewind(_in);
	if (y == 1)
		return;
	while ((c = fgetc(_in)) != EOF) {
		if (c == '\n') {
			_line++;
			if (_line == y)
				break;
		}
	}
}

PRIVATE void PrintNextLine(void) {

	int c;

	FPrintf(stdout, "; %04i : ", _line);
	if (!_in) {
		_line++;
		FPrintf(stdout, "\n");
		return;
	}
	while ((c = fgetc(_in)) != EOF) {
		if (c == '\n') {
			_line++;
			FPrintf(stdout, "\n");
			return;
		}
		FPrintf(stdout, "%c", c);
	}
}

PRIVATE void PrintNextLines(IN unsigned c) {

	while (c--)
		PrintNextLine();
}

#if 0

PRIVATE void PrintBlock(IN PINSTR_LIST list) {

	/*
		line k: _________ < line to display.
		        ^
		        XCOORD

		To display line k we need to consume it as well.
		This means <current line + 1> lines to draw.
	*/

	PINSTR ins;

	if (!list) return;
	for (ins = list->first; ins; ins = ins->next) {

		if (IsXCoord(ins)) {

			FPrintf(stdout, "\n");

			if (ins->coord.y < _line - 1) {

				// although there are cases where this is possible
				// via #line, for now will bugcheck this as this chould
				// not occur - at least for now:

				FPrintf(stderr, "\t; *** BUGCHECK? Coord %i Line %i *** %i\n", ins->coord.y, _line, OPCODE(ins->op));
				if (ins->next) {
					FPrintf(stderr, "\t%I  ", ins->next);
					FPrintf(stderr, "%x\n", ins->next);
				}
				__debugbreak();
			}
			PrintNextLines(ins->coord.y - _line + 1);
			FPrintf(stdout, "\n");
			continue;
		}

		FPrintf(stdout, "\t%I\n", ins);
	}
}
#endif


PRIVATE void PrintCode(IN PINSTR list) {

	/*
	line k: _________ < line to display.
	^
	XCOORD

	To display line k we need to consume it as well.
	This means <current line + 1> lines to draw.
	*/

	PINSTR ins;

	if (!list) return;
	for (ins = list; ins; ins = ins->next) {

		if (IsXCoord(ins)) {

			if (ins->coord.y == _line - 1)
				continue;

			FPrintf(stdout, "\n");

			if (ins->coord.y < _line - 1) {

				FPrintf(stderr, "\t; *** BUGCHECK? Coord %i Line %i *** %i\n", ins->coord.y, _line, OPCODE(ins->op));
				if (ins->next) {
					if (!IsXLabel(ins->next))
						FPrintf(stdout, "\t");
					FPrintf(stderr, "%I  ", ins->next);
					FPrintf(stderr, "%x\n", ins->next);
				}
				__debugbreak();
			}
			PrintNextLines(ins->coord.y - _line + 1);
			FPrintf(stdout, "\n");
			continue;
		}

		if (!IsXLabel(ins))
			FPrintf(stdout, "\t");
		FPrintf(stdout, "%I\n", ins);
	}
}

PRIVATE void OutFunction(IN PSYMBOL sym) {

//	PXBLOCK block;
	PSYMBOL local;
	PINSTR  ins;

//	for (ins = sym->xcode; ins; ins = ins->next) {
//		if (IsXCoord(ins)) {
//			printf("\nLINE = %i", ins->coord.y);
//		}
//	}

	Open(sym->coord.fname);
	Goto(sym->coord.y);

	FPrintf(stdout, "\n; Function compile flags");
	FPrintf(stdout, "\n; File filename");

	for (local = sym->localsListHead; local; local = local->nextLocal)
		FPrintf(stdout, "\n%A = %i ; stack size = %i", local->symbolic, local->offset, local->stacksize);

	FPrintf(stdout, "\nsegment .text");
	FPrintf(stdout, "\n%A:\n", sym->symbolic);

	PrintCode(sym->xcode);

//	for (block = sym->xcode; block; block = block->next) {
//		FPrintf(stdout, ".L%u:\n", block->name);
//		PrintBlock(block->ins);
//	}
}

PRIVATE OutData(PSYMBOL sym) {

	PNODE init;

	init = sym->ast;

	// external symbol
	if (sym->sclass == SC_EXTERN) {
		FPrintf(stdout, "extrn %A", sym->symbolic);
	}

	// global symbol
	if (sym->sclass != SC_EXTERN && sym->sclass != SC_STATIC) {
		FPrintf(stdout, "global %A", sym->symbolic);
	}

	// c-string:
	if (sym->type == ArrayOfCharType && sym->val.s) {
		FPrintf(stdout, "%A: db \"%A\"", sym->symbolic, sym->val.s);
	}

	// pointer-to-symbol:
	if (IsPointer(sym->type)) {
		if (init && init->sym)
			FPrintf(stdout, "%A: dd %A", sym->symbolic, init->sym->symbolic);
	}

	FPrintf(stdout, "\n");
}

PUBLIC void InitListing(void) {

	FPrintf(stdout, "; Listing file generated by Neptune C Compiler\n\n");
}

PUBLIC void EmitListing(IN PSYMBOL sym) {
	
	if (IsFunction(sym->type) && sym->code)
		OutFunction(sym);
	else
		OutData(sym);
}

